name: .NET

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '*/1 * * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2
    
    # .Net Core 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    # 发布
    - name: Publish
      run: |
        dotnet publish
    
    # 运行
    - name: run
      run: |
        cd bin/Debug/net5.0
        dotnet PushMusic.dll
