name: PushMusic

on:
 workflow_dispatch: # 手动触发
 schedule: # 计划任务触发
    - cron: '*/15 * * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出
    - name: Checkout
      uses: actions/checkout@v2
    
    # .Net Core 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    # 发布
    - name: Publish
      run: |
        dotnet publish --configuration Release --self-contained false --output ./publish
    
    # 运行
    - name: run
      run: |
        cd ./publish
        dotnet PushMusic.dll
