name: .NET

on:
  push:
    branches: [ main ]
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '0 */1 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'


    # .Net Core 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    # 还原
    - name: Restore dependencies
      run: dotnet restore
    
    # 生产
    - name: Build
      run: dotnet build --no-restore
    
    # 运行
    - name: run
      run: dotnet run
